config/routes.rb
Dogrescue::Application.routes.draw do

  root :to => "dogs#index"
  get "dogs" => "dogs#index"
  get "dogs/index"
  match "dogs/view/:id" => "dogs#view"

  get "admin" => "admin/dogs#index"
  get "admin/login" => "admin/sessions#new", :as => "admin_login"
  get "admin/logout" => "admin/sessions#destroy", :as => "admin_logout"

  namespace :admin do
    resources :users
    resources :sessions
    resources :dogs
  end

end

app/models/dog.rb
#Dog data model
class Dog < ActiveRecord::Base
  
  #Validation
  validates_presence_of :name, :breed, :status
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  
  #validation
  validates_presence_of :email
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_uniqueness_of :email
  
  #callback
  before_save :encrypt_password
  
  #Gets the full name
  def name
    first_name + " " + last_name
  end
  
  #Authenticate 
  def self.authenticate(email, password)
    
    #Get the user
    user = self.find_by_email(email)
    
    if user.nil?
      raise NoSuchUserError, "No user with email #{email}"
    end
    
    #If user checks out, return the user, else nil
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      raise WrongPasswordError, "Incorrect password"
    end
  end
  
  #Encrypt the password
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end  
  
end

#Exceptions for authentication
class NoSuchUserError < RuntimeError
end

class WrongPasswordError < RuntimeError
end

app/controllers/admin/dogs_controller.rb
class Admin::DogsController < ApplicationController
  
  before_filter :require_login
  layout "admin"
  
  # GET /admin/dogs
  def index
    @dogs = Dog.paginate(:page => params[:page])
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
    @dog = Dog.find(params[:id])
  end

  # POST /dogs
  # POST /dogs.json
  def create
    
    #handle upload
    handle_upload
    
    @dog = Dog.new(params[:dog])
    
    if @dog.save
      flash[:success] = "Dog was successfully created"
      redirect_to edit_admin_dog_path(@dog)
    else
      render action: "new" 
    end

  end

  # PUT /dogs/1
  # PUT /dogs/1.json
  def update
    
    #handle the upload
    handle_upload
    
    @dog = Dog.find(params[:id])

    if @dog.update_attributes(params[:dog])
      flash[:success] = "Dog was successfully updated"
      redirect_to edit_admin_dog_path(@dog)
    else
      render action: "edit"
    end

  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    flash[:success] = "Deleted dog"

    redirect_to admin_dogs_path

  end 
  
  
  protected 
  
  #Handle file upload
  def handle_upload
    if params[:dog][:image]  
      uploaded_io = params[:dog][:image]
      File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
      end
      params[:dog][:image] = uploaded_io.original_filename
    end
  end 
  
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  
  layout "admin"
  
  # Show the login screen
  def new

  end
  
  # POST method - do the login
  def create
    
    # Try logging in
    begin
      user = User.authenticate(params[:email], params[:password])
      session[:current_user_id] = user.id
      flash[:success] = "Welcome back #{user.name}"
      redirect_to admin_dogs_path
      
    #if the user doesn't exist
    rescue NoSuchUserError
      flash.now[:error] = "No user with email #{params[:email]}"
      @email = params[:email]
      render :action => "new"
      
    #if the wrong password is entered
    rescue WrongPasswordError
      @email = params[:email]
      flash.now[:error] = "Wrong password"
      render :action => "new"
    end
    
  end
  
  #Destroy the session. i.e. LOG OUT
  def destroy
    session[:current_user_id] = nil
    flash[:success] = "Logged out"
    redirect_to admin_login_path
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  #Set the layout to the admin layout
  layout "admin"
  
  #Requires a logged in user to use this controller
  before_filter :require_login
  
   # GET /admin/users
   def index
     @users = User.all
   end

   # GET /admin/users/new
   def new
     @user = User.new
   end

   # POST /admin/users
   def create
     @user = User.new(params[:user])

     if @user.save
       flash[:success] = "User was successfully created"
       redirect_to edit_admin_user_path(@user)
     else
       render "new"
     end

   end

   # GET /admin/users/1/edit
   def edit
     @user = User.find(params[:id])
   end

   # PUT /admin/users/1
   def update
     @user = User.find(params[:id])

     if @user.update_attributes(params[:user])
       flash[:success] = "User was successfully updated"
       redirect_to edit_admin_user_path(@user)
     else
       render "edit"
     end

   end

   # DELETE /admin/users/1
   def destroy
     @user = User.find(params[:id])
     @user.destroy
     flash[:success] = "Deleted user"
     redirect_to admin_users_url
     
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  #require login filter
  def require_login
    if logged_in?
      @current_user = get_logged_in_user
    else
      redirect_to admin_login_path
    end
  end
  
  #Checks if a user is logged in
  def logged_in?

    if session[:current_user_id]
      return true
    end
    
    #Default return false
    false
    
  end
  
  #Gets the logged in user
  def get_logged_in_user
    if logged_in?
      user = User.find(session[:current_user_id])
      if user
        return user
      else
        return nil
      end
    end
    
    #default return nil
    nil
  end
  
end

app/controllers/dogs_controller.rb
#Main controller for front end viewing of all the dogs
class DogsController < ApplicationController
  
  def index
    @dogs = Dog.where("status = 'available'").paginate(:page => params[:page])
  end

  def view
    @dog = Dog.find(params[:id])
  end

end

app/helpers/admin/dogs_helper.rb
module Admin::DogsHelper
  
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Based on https://gist.github.com/1205828, in turn based on https://gist.github.com/1182136
  class BootstrapLinkRenderer < ::WillPaginate::ActionView::LinkRenderer
    protected

    def html_container(html)
      tag :div, tag(:ul, html), container_attributes
    end

    def page_number(page)
      tag :li, link(page, page, :rel => rel_value(page)), :class => ('active' if page == current_page)
    end

    def gap
      tag :li, link(super, '#'), :class => 'disabled'
    end

    def previous_or_next_page(page, text, classname)
      tag :li, link(text, page || '#'), :class => [classname[0..3], classname, ('disabled' unless page)].join(' ')
    end
  end

  def page_navigation_links(pages)
    will_paginate(pages, :class => 'pagination', :inner_window => 2, :outer_window => 0, :renderer => BootstrapLinkRenderer, :previous_label => '&larr;'.html_safe, :next_label => '&rarr;'.html_safe)
  end

end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dogs/_form.html.erb
<%= form_for([:admin, @dog], :html => { :class => "form-stacked" }) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation" class="alert-message block-message error">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<% if @dog.image %>
	<%= image_tag "/uploads/#{@dog.image}" %><br />
	<%= @dog.image %>
	<% end %>

	<fieldset>
		
		<div class="clearfix">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div class="clearfix">
			<%= f.label :breed %>
			<%= f.text_field :breed %>
		</div>
		<div class="clearfix">
			<%= f.label :description %>
			<%= f.text_area :description, :style => "width: 300px; height: 100px;" %>
		</div>
		<div class="clearfix">
			<%= f.label :status %>
			<%= f.select(:status, [['Available', 'available'], ['Not available', 'not available']]) %>
		</div>
		
		<div class="clearfix">
			<%= f.label :image %>
			<%= f.file_field :image %>
		</div>

	</fieldset>
	
  <div class="clearfix">
    <%= f.submit :class => "btn primary" %>
  </div>
<% end %>

app/views/admin/dogs/edit.html.erb
<h1>Editing <%= @dog.name %></h1>

<% if flash[:success] %>
<div class="alert-message success">
	<p><%= flash[:success] %></p>
</div>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', admin_dogs_path %>

app/views/admin/dogs/index.html.erb
<h1>Listing dogs</h1>

<% if flash[:success] %>
<div class="alert-message success">
	<p><%= flash[:success] %></p>
</div>
<% end %>

<p>
	<%= link_to 'New Dog', new_admin_dog_path, :class => "btn primary" %>
</p>

<table>
  <tr>
	<th>Image</th>
    <th>Name</th>
    <th>Breed</th>
    <th>Description</th>
    <th>Status</th>
    <th></th>
    <th></th>
  </tr>

<% @dogs.each do |dog| %>
  <tr>
	<td><%= link_to(image_tag("/uploads/#{dog.image}", :style => "width: 150px;"), edit_admin_dog_path(dog)) %></td>
    <td><%= dog.name %></td>
    <td><%= dog.breed %></td>
    <td><%= truncate(dog.description, :length => 250) %></td>
    <td><%= dog.status %></td>
    <td><%= link_to 'Edit', edit_admin_dog_path(dog) %></td>
    <td><%= link_to 'Destroy', admin_dog_path(dog), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<%= page_navigation_links @dogs %>

app/views/admin/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_dogs_path %>

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user], :html => {:class => "form-stacked"}) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert-message block-message error">
		<p><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p>

		<ul>
		<% @user.errors.full_messages.each do |msg| %>
		  <li><%= msg %></li>
		<% end %>
		</ul>
    </div>
  <% end %>

	<fieldset>

		<div class="clearfix">
		  <%= f.label :email %>
		  <%= f.text_field :email %>
		</div>
		
		<div class="clearfix">
		  <%= f.label :password %>
		  <%= f.password_field :password %>
		</div>
		
		<div class="clearfix">
		  <%= f.label :password_confirmation %>
		  <%= f.password_field :password_confirmation %>
		</div>

		<div class="clearfix">
		  <%= f.label :first_name %>
		  <%= f.text_field :first_name %>
		</div>
		
		<div class="clearfix">
		  <%= f.label :last_name %>
		  <%= f.text_field :last_name %>
		</div>

	</fieldset>
	
  <div class="actions">
    <%= f.submit :class => "btn primary" %>
  </div>

<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<% if flash[:success] %>
<div class="alert-message success">
	<p><%= flash[:success] %></p>
</div>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<% if flash[:success] %>
<div class="alert-message success">
	<p><%= flash[:success] %></p>
</div>
<% end %>

<table>
  <tr>
    <th>Email</th>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
    <td><%= link_to 'Destroy', [:admin, user], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_admin_user_path, :class => "btn primary" %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/dogs/index.html.erb
<h1>Dog Rescue</h1>
<p>Check out all the dogs available for adoption:</p>

<div class="dogs">
	<% @dogs.each do |dog| %>
		<div class="dog">
			<div class="dog_image"><%= link_to( image_tag("/uploads/#{dog.image}"), "/dogs/view/#{dog.id}" ) %></div>
			<div class="dog_description">
				<h1><%= dog.name %></h1>
				<p><%= truncate(dog.description, :length => 255) %></p>
				<p><%= link_to "View more", "/dogs/view/#{dog.id}" %></p>
			</div>
		</div>
		<div class="clearfix">
		
	<% end %>
</div>

app/views/dogs/view.html.erb
<h1><%= @dog.name %></h1>
<p><%= image_tag "/uploads/#{@dog.image}" %></p>
<p><%= @dog.description %></p>
<p>
	<b>Breed: </b> <%= @dog.breed %> <br />
	<b>Availability: </b> <%= @dog.status %>
</p>
<p><%= link_to "Back", dogs_path %></p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dogrescue Admin</title>
  <%= stylesheet_link_tag "bootstrap" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding: 60px;">
	
	<% # Only show the top bar if logged in %>
	<% if @current_user %>
	<div class="topbar">
		<div class="topbar-inner">
			<div class="container">
				<h3><a href="/admin">Dog Rescue</a></h3>
				<ul class="nav">
					<li><a href="/admin/dogs">Dogs</a></li>
					<li><a href="/admin/users">Users</a></li>
				</ul>
				<ul class="nav" style="float: right;">
					<li><%= link_to 'Logout', admin_logout_path %></li>
				</ul>
			</div>
		</div>
	</div>
	<% end %>
	
	<div class="container">
		
		<div class="row">
			<div class="span16">
				<%= yield %>
			</div>
		</div>
		
	</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dogrescue</title>
  <%= stylesheet_link_tag "960", "application", controller_name %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<div class="container_12">		
		<div class="grid_12">
			<%= yield %>
		</div>
	</div>

</body>
</html>